# Travis config for PHP library
#
# Normal build - only phpunit
# Build with checks:
# - code sniffer
# - phpunit with coverage
# - sending coverage data to coveralls.io
#
# Checks are used only for one version (PHP 5.4)

language: php

matrix:
  include:
    - php: 5.4
      env: CHECKS=yes
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
      # Travis HHVM does not support XDebug
      env: NOXDEBUG=yes

sudo: false

before_install:
  # Disable xdebug for composer (https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer)
  # Do not use `phpenv config-rm` because we need xdebug.ini for enable it for phpunit coverage.
  - if [ ! "$NOXDEBUG" = "yes" ]; then mv /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini .; fi;
  # Travis container may contain outdated version of composer
  - composer self-update

install:
  - ls -la /home/travis/.phpenv/versions/$(phpenv version-name)/bin/
  # Composer can not used dist (github required the auth token). Just specify prefer-source.
  - composer install --prefer-source
  # In order not to litter in the local dev-version specify checks-packages here instead composer.json
  - composer require phpunit/phpunit --prefer-source
  - if [ "$CHECKS" = "yes" ]; then composer require squizlabs/php_codesniffer="~2.3" --prefer-source; fi;
  - if [ "$CHECKS" = "yes" ]; then composer require satooshi/php-coveralls --dev --prefer-source; fi;
  # Generate the coveralls config (not to keep it in the repo)
  - >
    if [ "$CHECKS" = "yes" ]; then 
        echo "src_dir: ." > .coveralls.yml &&
        echo "json_path: coveralls-upload.json" >> .coveralls.yml &&
        echo "coverage_clover: clover.xml" >> .coveralls.yml;
    fi;

script:
  # Normal run - only phpunit
  - if [ ! "$CHECKS" = "yes" ]; then php vendor/bin/phpunit; fi;
  # Run with checks
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=vendor .; fi;
  # Enable xdebug for coverage
  - if [ "$CHECKS" = "yes" ]; then phpenv config-add xdebug.ini $EXT_DIR; fi;
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/phpunit --coverage-clover clover.xml; fi;
  # Coveralls in `script` section instead `after_succes` for build fail if when error
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/coveralls -c .coveralls.yml; fi;

notifications:
  email:
    on_success: change
    on_failure: always
