language: php

matrix:
  include:
    - php: 5.4
      env: CHECKS=yes
   # - php: 5.5
   # - php: hhvm
   #   env: NOXDEBUG=yes

sudo: false

before_install:
  - pwd
  - LOCAL_DIR="build"
  - XDEBUG_FILE="/home/travis/.phpenv/versions/5.4/etc/conf.d/xdebug.ini"
  - phpenv --help
  - if [ ! "$NOXDEBUG" = "yes" ]; then 
        mkdir -p $LOCAL_DIR &&
        mv $XDEBUG_FILE $LOCAL_DIR;
    fi;
  - composer self-update

install:
  - composer install
  - >
    if [ "$CHECKS" = "yes" ]; then 
        composer require satooshi/php-coveralls --dev &&
        composer require squizlabs/php_codesniffer="~2.3"
    fi;

script:
  - >
    if [ "$CHECKS" = "yes" ]; then 
        mv $XDEBUG_FILE $LOCAL_DIR &&
        mkdir -p build/logs &&
        phpunit --coverage-clover build/logs/clover.xml &&
        [[ -e build/logs/clover.xml ]] &&
        php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=vendor .
    else
        phpunit;
    fi;

after_success:
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/coveralls -c .coveralls.yml; fi;

notifications:
  email:
    on_success: change
    on_failure: always
