language: php

matrix:
  include:
    - php: 5.4
      env: CHECKS=yes
    - php: 5.5
    - php: hhvm
      env: NOXDEBUG=yes

sudo: false

before_install:
  - ll /home/travis/.phpenv/versions/5.4/etc/conf.d
  - cat /home/travis/.phpenv/versions/5.4/etc/conf.d/xdebug.ini  
  - if [ ! "$NOXDEBUG" = "yes" ]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

install:
  - composer install
  - if [ "$CHECKS" = "yes" ]; then composer require satooshi/php-coveralls --dev; fi;
  - if [ "$CHECKS" = "yes" ]; then composer require squizlabs/php_codesniffer="~2.3" --dev; fi;

script:
  - if [ "$CHECKS" = "yes" ]; then mkdir -p build/logs; fi;
  - if [ "$CHECKS" = "yes" ]; then phpunit --coverage-clover build/logs/clover.xml; else phpunit; fi;
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=vendor .; fi;

after_success:
  - if [ "$CHECKS" = "yes" ]; then php vendor/bin/coveralls -c .coveralls.yml; fi;

notifications:
  email:
    on_success: change
    on_failure: always
